modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="nuggetmod"
version="${file.jarVersion}"
displayName="Nugget Mod"
authors="NoEffort"
description='''
Nothing to see here!
'''
[[dependencies.nuggetmod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nuggetmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
